#!/bin/sh

ssh user@xx.xx.xx.xx <<EOF
  cd kapi
  git pull kycapi
  source env/bin/activate
  ./manage.py migrate
  sudo systemctl restart nginx
  sudo service gunicorn restart
  sudo service nginx restart
  exit
EOF
