#!/bin/sh

ssh ubuntu@3.215.162.250 <<EOF
  cd kapi
  git pull kycapi
  source env/bin/activate
  ./manage.py migrate
  sudo systemctl restart nginx
  sudo service gunicorn restart
  sudo service nginx restart
  exit
EOF
